version: '3.7'

services:
  django:
    build: ./chat_ws
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./chat_ws/:/usr/src/chat_ws/
    ports:
      - 8000:8000
    env_file:
      - ./.env

  vue:
    image: node:lts-alpine
    working_dir: /app
    command:
      sh -c "npm install && npm run serve --host=0.0.0.0 --port=8080"
    volumes:
      - ./chat_vue/:/chat_vue